package com.glimmer.app.data

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import kotlinx.coroutines.flow.Flow

@Dao
interface BirthdayDao {
    @Query("SELECT * FROM birthdays ORDER BY dateOfBirth ASC")
    fun getAllBirthdays(): Flow<List<Birthday>>

    // Returns the generated row id — callers need it to schedule an alarm keyed to the real id
    // rather than the default `id = 0` every unsaved Birthday carries.
    @Insert(onConflict = OnConflictStrategy.ABORT)
    suspend fun insertBirthday(birthday: Birthday): Long

    @Update
    suspend fun updateBirthday(birthday: Birthday)

    @Query("DELETE FROM birthdays WHERE id = :id")
    suspend fun deleteBirthdayById(id: Int)

    @Query("SELECT * FROM birthdays WHERE id = :id")
    fun getBirthdayById(id: Int): Flow<Birthday?>

    // COLLATE NOCASE so "Sam" and "sam" count as the same person; `id != :excludeId` lets Edit
    // check against every OTHER row without always matching itself. -1 never matches a real
    // autogenerated id, so the default is safe to use unconditionally from Add.
    @Query("SELECT EXISTS(SELECT 1 FROM birthdays WHERE name = :name COLLATE NOCASE AND dateOfBirth = :dateOfBirth AND id != :excludeId)")
    suspend fun existsByNameAndDate(name: String, dateOfBirth: Long, excludeId: Int = -1): Boolean
}
